epochs: 20
dtype: float16
accumulation_steps: 1
grad_clip: 5.0
log_interval: 100
log_every_n_steps: 100
val_check_interval: 1.0
save_top_k: 3
out_dir: out
checkpoint_path: ''
exp_name: image-compression
log_dir: ./logs
seed: 17
precision: 16-mixed
num_gpus: 1
resume_from_checkpoint: null
dataset:
  dataset_type: waymo
  data_dir: /workspace/data
  batch_size: 16
  n_frames: 1
  crop: 128
  yuv_format: ''
  num_workers: 4
  video_dir: ''
optimizer:
  optimizer_type: adam
  base_lr: 1e-4
  min_lr: 1e-5
  aux_lr: 5e-4
  weight_decay: 0.01
  warmup_iters: 0
compression:
  lambda_min: 1.0
  lambda_max: 768.0
  q_levels: 64
  lambda_multiplier: 10.0
